import './FactOfTheDay.css';

/*
National Day widget made by caminus.neocities.org! Feel free to copy this, modify it, or do whatever you'd like with it.
Add your birthday or your pet's adoption date. This is all for fun.
It will create a <div id="natday"></div> wherever the script is inserted. #natday can be styled however you like.
Linking back to me is appreciated but not necessary. Keep this message intact, or not. The code is yours!
*/



function FactOfTheDay () 
{
  const days = {
  "01-01": "é ano novo!!!",
  "01-02": "é dia mundial dos introvertidos, vamos ficar em casa hoje!!",
  "01-03": "é Dia Internacional do Bem-Estar da Mente e do Corpo, vamos meditar juntos :D",
  "01-04": "é o dia mundial do Braile",
  "01-05": "é o aniversario da criação da primeira tipografia do Brasil, a Impressão Régia",
  "01-06": "é dia da gratidão, OBRIGADO!",
  "01-07": "é o dia do leitor, quantos livros você prometeu de ler esse ano?",
  "01-08": "é o dia do fotografo, click click!",
  "01-09": "nesse dia em 1431 o julgamento da Joana d'Arc começou, e em 1822 foi o dia do Fico",
  "01-10": "foi o dia da primeira assembléia geral das nações unidas",
  "01-11": "é o dia do controle da poluição por agrotóxicos, apoie o seu pequeno produtor local!",
  "01-12": "é o dia em que o Exército Vermelho inicia a grande Ofensiva no Vístula-Oder contra as forças nazistas",
  "01-13": "é o dia da Assinatura do Tratado de Madrid, que substituiu o Tratado de Tordesilhas",
  "01-14": "é o dia internacional da pipa",
  "01-15": "é o dia mundial do compositor, dia de criar uma música em?",
  "01-16": "é o dia dos Cortadores de Cana de Açúcar, agradeça pelo seu melado e por suas pingas!",
  "01-17": "é o dia em que as forças soviéticas e polonesas realizaram a libertação de Varsóvia",
  "01-18": "é o dia internacional do riso :))))",
  "01-19": "é o dia da inauguração da Dutra, rodovia que liga as capitais do Rio e de São Paulo",
  "01-20": "é o dia mundial do queijo, uma das 9 maravilhas do mundo <3",
  "01-21": "é o dia em que Vladimir Lênin, líder da Revolução Russa e principal nome por trás da criação da União Soviética, faleceu aos 53 anos :(",
  "01-22": "é o dia do trabalhador doméstico",
  "01-23": "é o Dia Internacional da Medicina Integrativa",
  "01-24": "é o Dia Internacional da Educação, abrace seu professor hoje",
  "01-25": "é o dia da criação dos Correios e Telégrafos no Brasil além de ser o dia do carteiro",
  "01-26": "é o dia da insurreição pernambucana, vaze holandeses",
  "01-27": "é o Dia Internacional em Memória às Vítimas do Holocausto",
  "01-28": "é o Dia Internacional da Privacidade de Dados",
  "01-29": "é o dia nacional da visibilidade Trans",
  "01-30": "é um dia com tempeiro de vó, dia da Saudade",
  "01-31": "é o Dia Nacional das Reservas Particulares do Patrimônio Natural, Focado em conscientizar a população sobre a conservação da biodiversidade local",
  "02-01": "Dia do tomate :)",
  "02-02": "é Dia de Iemanjá, Axé",
  "02-03": "é o dia nacional do bolo de cenoura, e eu aprendi isso com um gringo",
  "02-04": "é o Dia Mundial contra o Câncer, va fazer seu toque",
  "02-05": "é o dia em que a Apollo 14 pousou na lua",
  "02-06": "é o Dia Internacional da Internet Segura, mate uma big tech hoje",
  "02-07": "é deflagrada a grande greve operária em São Paulo liderada por João da Costa Pimenta, marco que instituiu a comemoração do Dia do Gráfico",
  "02-08": "uma iniciativa global para promover a conscientização sobre a doença e combater o estigma associado a ela deu origem ao Dia da Epilepsia",
  "02-09": "a missão Apollo 14 voltou para a terra e o volêi foi criado",
  "02-10": "é o Dia Mundial das Leguminosas, compre com seu pequeno produtor local!",
  "02-11": "é Dia Internacional das Mulheres e Meninas na Ciência, girl power!",
  "02-12": "nasce o naturalista inglês Charles Darwin, data hoje celebrada internacionalmente como o Dia de Darwin para homenagear suas contribuições à ciência e à teoria da evolução.",
  "02-13": "o astrônomo italiano Galileu Galilei chega a Roma para ser julgado pela Santa Inquisição",
  "02-14": "é o Dia Internacional da Doação de Livros",
  "02-15": "é Lupercália!!!  Um festival histórico, considerado por muitos historiadores como uma das origens das tradições de afeto e amor que hoje culminam no Dia dos Namorados.",
  "02-16": "Após a Revolução Cubana, Fidel Castro assumiu o cargo de primeiro-ministro do país.",
  "02-17": "o supercomputador Deep Blue, da IBM, derrota pela primeira vez o então campeão mundial Garry Kasparov em uma partida(1996)",
  "02-18": "surge a primeira faculdade de medicina do Brasil, a Escola de Cirurgia da Bahia (atual Faculdade de Medicina da Universidade Federal da Bahia)",
  "02-19": "foi instituído o Parque Nacional da Amazônia, o maior parque nacional do país",
  "02-20": "é o Dia Mundial da Justiça Social",
  "02-21": "é o aniversário do meu irmão :D, parabéns mano",
  "02-22": "petróleo jorra pela primeira vez em território brasileiro, no poço de Lobato, localizado em Salvador, Bahia",
  "02-23": "foi realizado o primeiro transplante de órgão bem-sucedido, representando um avanço para a medicina moderna (1954)",
  "02-24": "Karl Marx e Friedrich Engels publicam em Londres o Manifesto Comunista em 1848",
  "02-25": "celebra o marco de 1957 em que foi realizado o primeiro teste com o dispositivo que devolve a audição",
  "02-26": "é o dia de contar um conto de fadas! (sim essa data comemorativa existe mesmo)",
  "02-27": "em 1879 o adoçante artificial Sacarina foi descoberto",
  "02-28": "é o dia da ressaca, beba bastante agua hoje!!",
  "02-29": "uau, um dia a mais, isso é raro",
  "03-01": "a sonda soviética Venera 3 atinge a superfície de Vênus, tornando-se a primeira nave a alcançar outro planeta em 1966",
  "03-02": "os primeiros CDs e reprodutores de áudio são lançados em 1983",
  "03-03": "é o dia mundial da vida selvagem, abraçe uma jaguatirica hoje!",
  "03-04": "dia de nascimento (1910) do Tancredo Neves, que seria eleito o primeiro presidente civil após a ditadura militar",
  "03-05": "Filatelista são aqueles que colecionam e estudam sobre selos e história postal, e hoje é o dia deles!",
  "03-06": "nesse dia, em 2013, foi a data de falescimento do Chorão :(",
  "03-07": "em 1958 foi fundada a sociedade brasileira de paleontologia",
  "03-08": "é o dia internacional da mulher!",
  "03-09": "é o dia internacional do DJ, uéca uéca",
  "03-10": "é o dia do Mario (MAR10)! wahoo!",
  "03-11": "em 1991 entrava em vigor o código de defesa do consumidor no Brasil",
  "03-12": "é o Dia do bibliotecário, você lembrou de devolver seu livro?",
  "03-13": "ocorre a Batalha do Jenipapo no Piauí (1823), marco fundamental e sangrento pela consolidação da Independência do Brasil",
  "03-14": "é o dia internacional da matemática (ou o dia do pi 3,14)!",
  "03-15": "é o dia da escola, abraçe seu professor hoje",
  "03-16": "é o Dia Nacional de Conscientização sobre as Mudanças Climáticas",
  "03-17": "é Dia de São Patricio (St. Patrick's Day) é dia de usar verde e beber cerveja!",
  "03-18": "em 1965 o cosmonauta soviético Aleksei Leonov realiza a primeira caminhada espacial da história",
  "03-19": "é dia nacional do artesão (e também dia do carpinteiro e marceneiro)",
  "03-20": "da-se inicio ao outono, são as aguas de março fechando o verão!",
  "03-21": "em 1963 nascia de Mauricio de Souza a personagem Mônica (da turma dela) e em 1980 nasceu Ronaldinho Gaúcho, personagens que possuem alguma certa semelhança",
  "03-22": "é o Dia Mundial da Agua, se hidrate!",
  "03-23": "é o Dia Mundial da Meteorologia, quantas previsões de tempo acertaram na sua cidade esta semana?",
  "03-24": "é a data que registra a descoberta do bacilo da tuberculose em 1882, comemorando o Dia Mundial da Tuberculose",
  "03-25": "é outorgada a primeira constituição do Brasil pelo imperador Dom Pedro I, fato que posteriormente deu nome à famosa rua de comércios em São Paulo (25 de Março)",
  "03-26": "é o Dia do Cacau, chocolate é bom dmaisi",
  "03-27": "é o Dia do Circo, de parabéns ao seu amigo!",
  "03-28": "é o dia do revisor no Brasil",
  "03-29": "é data da fundação da primeira capital do Brasil, Salvador (em 1549)",
  "03-30": "o  O astronauta brasileiro Marcos Pontes decola a bordo da nave Soyuz TMA-8 rumo à Estação Espacial Internacional, tornando-se o primeiro sul-americano e lusófono no espaço",
  "03-31": "foi o início do Golpe de Estado no Brasil em 1964, que depôs o presidente eleito João Goulart",
  "04-01": "é primeiro de abril, dia de se declarar sem medo da rejeição",
  "04-02": "é o dia mundial da conscientização do autismo",
  "04-03": "foi realizada a primeira chamada de telefone móvel portátil da história, em 1983",
  "04-04": "é o dia nacional do parkinsoniano",
  "04-05": "é Pascoa! não a data do chocolate pois ela varia, a data da descoberta das ilhas de Páscoa em 1722",
  "04-06": "é o dia internacional da assexualidade",
  "04-07": "é o Dia Mundial da Saúde",
  "04-08": "em 1888 o famoso quadro de independencia ou morte que sempre vemos em livros de história, de Pedro Américo, foi exposto ao publico pela primeira vez",
  "04-09": "é o Dia Nacional do Aço, que homenageia a criação da Companhia Siderurgica Nacional",
  "04-10": "é o Dia Mundial da Homeopatia, quem diria que pseudociência também tem dia né? você está bebendo agua",
  "04-11": "é o Dia do Infectologista",
  "04-12": "é o Dia do Obstetra",
  "04-13": "um tanque de oxigênio explode a bordo da missão Apollo 13, comprometendo a viagem e dando origem à famosa frase 'Houston, temos um problema'",
  "04-14": "É O DIA MUNDIAL DO CAFÉÉÉÉ",
  "04-15": "é o Dia Nacional da Conservação do Solo",
  "04-16": "é o Dia Nacional da Lembrança do Holocausto",
  "04-17": "é o Dia Nacional de Luta pela Reforma Agrária",
  "04-18": "em 1955 morre Albert Einstein",
  "04-19": "é o Dia dos Povos Indígenas no Brasil",
  "04-20": "você sabe que dia é hoje, blaze it hehe",
  "04-21": "meu aniversário :) parabéns preu",
  "04-22": "é dia do Descobrimento do Brasil, poderia ter sido meu aniversário também, minha mãe pode escolher kkkkkkk",
  "04-23": "é o Dia Mundial do Livro",
  "04-24": "é o Dia Nacional da Língua Brasileira de Sinais",
  "04-25": "é o Dia Mundial da Malária",
  "04-26": "é o Dia Internacional em Memória do Desastre de Chernobil",
  "04-27": "é o Dia da Empregada Doméstica, como minha vó já foi ^.^",
  "04-28": "é o Dia Mundial da Segurança e Saúde no Trabalho",
  "04-29": "é o Dia Internacional da Dança, vamos dançar um forrózinho?",
  "04-30": "é o Dia Nacional da Mulher, Girl Power!",
  "05-01": "é o Dia do Trabalhador, falte no seu emprego!",
  "05-02": "é o Dia Mundial do Atum, perfeito para fazer um bom 'sushi de pobre'",
  "05-03": "é o Dia Mundial da Liberdade de Imprensa",
  "05-04": "é dia de Star Wars, 'May the 4th be with you'",
  "05-05": "é o Dia Mundial da Lingua Portuguesa",
  "05-06": "é o Dia do Cartógrafo e da Coragem",
  "05-07": "em 1945 a Alemanha nazista assina o termo de rendição incondicional aos Aliados em Reims, França, marcando o fim iminente da Segunda Guerra Mundial na Europa",
  "05-08": "é o Dia Internacional da Cruz Vermelha",
  "05-09": "Wilhelm Keitel ratifica a rendição incondicional da Alemanha nazista em Berlim, formalizando o fim da Segunda Guerra Mundial para a União Soviética — data celebrada como o Dia da Vitória",
  "05-10": "é o Dia do Guia de Turismo",
  "05-11": "é a Inauguração oficial do Telégrafo no Brasil",
  "05-12": "é o Dia Mundial do Enfermeiro",
  "05-13": "é a data da Abolição da Escravatura no Brasil em 1888",
  "05-14": "No Brasil, o dia ficou historicamente marcado como o 'dia seguinte' à assinatura da Lei Áurea, quando a população negra recém-libertada foi deixada à própria sorte, sem acesso a terras, moradia ou trabalho",
  "05-15": "é o Dia Internacional da Família",
  "05-16": "é o Dia do Gari",
  "05-17": "é o Dia Iternacional Contra a Homofobia",
  "05-18": "é o Dia Nacional da Luta Antimanicomial",
  "05-19": "é o Dia Nacional de combate à Cefaleia",
  "05-20": "é Dia Mundial da Abelha, agradeça uma Abelha",
  "05-21": "é o Dia da Lingua Nacional",
  "05-22": "é o Dia Internacional da Biodiversidade e o Dia do Abraço",
  "05-23": "é o Dia Mundial da Tartaruga",
  "05-24": "em 1543 morre Nicolau Copérnico, astrônomo que propôs o modelo heliocêntrico",
  "05-25": "é o Dia do Orgulho Nerd (ou Dia da Toalha)",
  "05-26": "é o Dia Nacional do Combate ao Glaucoma",
  "05-27": "é o Dia Nacional da Mata Atlântica",
  "05-28": "é o Dia Mundial do Hamburguer, já escolheu qual você vai pedir hoje?",
  "05-29": "é o Dia do Geógrafo",
  "05-30": "um pouco diferente de ontem, hoje é dia do Geólogo",
  "05-31": "é o Dia Mundial sem Tabaco! cingaro faz mal cara!",
  "06-01": "em 1808 foi publicada a primeira edição do Correio Braziliense, marco que institui a celebração do Dia da Imprensa no Brasil",
  "06-02": "é o Aniversário dos Lençóis Maranhenses",
  "06-03": "é o Dia Mundial da Bicicleta, hora de ir pro Spinning!",
  "06-04": "é o Dia Internacional das Crianças Vítimas de Agressão",
  "06-05": "é o Dia Mundial do Meio Ambiente",
  "06-06": "é o Dia Nacional de Luta contra Queimaduras, se seu óleo pegar fogo não jogue agua, tampe!",
  "06-07": "é o Dia Mundial da Segurança Alimentar",
  "06-08": "é o Dia Mundial dos Oceanos",
  "06-09": "é o Dia Naciona da Imunização, tome suas vacinas e viva o SUS",
  "06-10": "é o Dia da Lingua Portuguesa",
  "06-11": "foi a data de estréia do filme E.T nos EUA em 1982",
  "06-12": "é Dia dos Namorados, de um beijo no seu benzinho",
  "06-13": "é o Dia Mundial da Conscientização do Albinismo",
  "06-14": "é o Dia Mundial do Doador de Sangue, doe sangue e salve vidas!",
  "06-15": "é o Dia Mundial da Conscientização da Violência contra a Pessoa Idosa",
  "06-16": "é o Dia Internacional da Tartaruga Marinha",
  "06-17": "é o Dia Mundial de Combate à Desertificação e à Seca",
  "06-18": "a imigração japonesa no Brasil começa quando 781 pessoas chegam ao Porto de Santos a bordo do navio Kasato Maru",
  "06-19": "é Dia do Cinema Brasileiro",
  "06-20": "é o Dia Mundial do Refugiado",
  "06-21": "começa o inverno, lembrou de lavar seus cobertores?",
  "06-22": "é o Dia do Aeroviário",
  "06-23": "é o Dia Internacional das Mulheres na Engenharia",
  "06-24": "finalmente temos Festas Juninas, pula fogueira iaia",
  "06-25": "é o Dia Mundial do Vitiligo e também o dia de morte do Michael Jackson (2009)",
  "06-26": "é o Dia Internacional Contra o Abuso e Tráfico Ilícito de Drogas",
  "06-27": "é o Dia Nacional do Volei!",
  "06-28": "é o Dia Internacional do Orgulho LGBTQIAPN+",
  "06-29": "a data da conquista da primeira Copa do Mundo pela Seleção Brasileira em 1958",
  "06-30": "é o Dia das Redes Sociais",
  "07-01": "começa o Mês do Orgulho!",
  "07-02": "é a Consolidação da Independencia do Brasil",
  "07-03": "é o Dia Nacional de Combate à Discriminação Racial",
  "07-04": "data do Falecimento da física e química Marie Curie, primeira mulher a ganhar um Prêmio Nobel e a única pessoa a recebê-lo em duas áreas científicas distintas (Física e Química)",
  "07-05": "é o Dia Mundial da Capoeira",
  "07-06": "é o Dia da Criação do IBGE",
  "07-07": "é o Dia Mundial do Chocolate",
  "07-08": "é o Dia do Panificador",
  "07-09": "marca o início da Revolução Constitucionalista de 1932 em São Paulo",
  "07-10": "é Dia da Pizza hmmmm",
  "07-11": "é o Dia Nacional do Socorrista",
  "07-12": "é o Dia Nacional do Funk",
  "07-13": "é o Dia Mundial do Rock",
  "07-14": "é o Dia da Liberdade de Pensamento",
  "07-15": "",
  "07-16": "it's Fresh Spinach Day!",
  "07-17": "it's National Peach Ice Cream Day in the US!",
  "07-18": "it's Nelson Mandela International Day!",
  "07-19": "on this day in 64, the Great Fire of Rome starts, rages for six days, and destroys half the city.",
  "07-20": "it's National Fortune Cookie Day in the US! What's your fortune?",
  "07-21": "it's Junk Food Day, mmmmm...",
  "07-22": "it's Pi Approximation Day! 22 over 7 is a good enough reason to eat some pie!",
  "07-23": "it's National Vanilla Ice Cream Day in the US!",
  "07-24": "it's Children's Day in Vanuatu!",
  "07-25": "it's National Hot Fudge Sundae Day in the US!",
  "07-26": "it's International Day for the Conservation of the Mangrove Ecosystems!",
  "07-27": "it's National Sleepy Head Day in Finland!",
  "07-28": "it's World Nature Conservation Day!",
  "07-29": "Garfield's favorite day, National Lasagna Day!!",
  "07-30": "it's International Day of Friendship!",
  "07-31": "it's National Raspberry Cake Day in the US!",
  "08-01": "the start of South Asian Heritage Month in the UK!",
  "08-02": "it's International Friendship Day!",
  "08-03": "on this day in 1527 John Rut sends the first letter from North America to Europe!",
  "08-04": "it's International Clouded Leopard Day!",
  "08-05": "it's World Tomistoma Day! That's a genus of crocodilian!",
  "08-06": "it's National Root Beer Float Day in the US!",
  "08-07": "it's Youth Day in Kiribati!",
  "08-08": "it's International Moon Bear Day!",
  "08-09": "artist Tove Jansson's birthday! She made Moomins!",
  "08-10": "it's World Lion Day! Rawr!!!",
  "08-11": "it's Mountain Day in Japan!",
  "08-12": "World Elephant Day! Also, World Hirola Day, a critically endangered antelope!",
  "08-13": "it's International Lefthanders Day!",
  "08-14": "it's National Navajo Code Talkers Day!",
  "08-15": "it's National Lemon Meringue Pie Day in the US!",
  "08-16": "it's Daimonji in Japan! Big bonfires are lit!",
  "08-17": "Mae West's birthday!",
  "08-18": "it's National Science Day in Thailand!",
  "08-19": "it's World Orangutan Day!",
  "08-20": "it's World Mosquito Day! Commemorating the discovery that they carry... malaria...",
  "08-21": "it's World Senior Citizen's Day! Do something nice for an older person!",
  "08-22": "it's National Eat A Peach Day in the US!",
  "08-23": "on this day in 79, Mount Vesuvius begins stirring... and it's the feast of Vulcan, god of fire!",
  "08-24": "it's National Waffle Day in the US!",
  "08-25": "it's National Banana Split Day in the US!",
  "08-26": "it's World African Wild Dog Day!",
  "08-27": "it's National Banana Lovers Day in the US!",
  "08-28": "it's National Cherry Turnover Day in the US!",
  "08-29": "it's International Day against Nuclear Tests!",
  "08-30": "it's International Whale Shark Day!",
  "08-31": "it's Trail Mix Day!",
  "09-01": "it's World Beach Day!",
  "09-02": "it's National Blueberry Popsicle Day in the US!",
  "09-03": "on this day in 1189 Richard the Lionheart is crowned king!",
  "09-04": "it's National Macadamia Nut Day in the US!",
  "09-05": "it's Amazon Rainforest Day!",
  "09-06": "on this day in 1628 the Puritans settled in Salem.",
  "09-07": "it's International Day of Clean Air for blue skies!",
  "09-08": "it's World Physical Therapy Day!",
  "09-09": "it's Chrysanthemum Day in Japan!",
  "09-10": "it's World Suicide Prevention Day!",
  "09-11": "it's National Hot Cross Bun Day, not just a song!",
  "09-12": "it's World Dolphin Day!",
  "09-13": "it's National Peanut Day in the US!",
  "09-14": "it's Hoagie Day!",
  "09-15": "it's International Colugo Day! That's a flying lemur!!",
  "09-16": "it's International Day for the Preservation of the Ozone Layer!",
  "09-17": "it's World Manta Day!",
  "09-18": "it's World Water Monitoring Day, so test your water!",
  "09-19": "it's Talk like a Pirate Day, yarr!!",
  "09-20": "it's National Punch Day in the US! The drink, not the verb.",
  "09-21": "that means you better remember tonight!",
  "09-22": "it's Car Free Day! Try a bus, train, or something else if you can!",
  "09-23": "it's Celebrate Bisexuality Day!",
  "09-24": "it's World Gorilla Day!",
  "09-25": "bell hooks' birthday!",
  "09-26": "it's World Cassowary Day! It's a freaky looking bird!",
  "09-27": "it's World Tourism Day!",
  "09-28": "it's World Rabies Day!",
  "09-29": "it's International Day of Awareness of Food Loss and Waste! Around 17% of food is wasted worldwide!",
  "09-30": "it's National Hot Mulled Cider Day in the US!",
  "10-01": "it's World Vegetarian Day! Go eat a plant!",
  "10-02": "Mahatma Gandhi's birthday!",
  "10-03": "it's Mean Girls Day! Wear something pink!",
  "10-04": "it's World Animal Day!",
  "10-05": "it's World Teachers' Day!",
  "10-06": "it's National Badger Day!",
  "10-07": "Simon Cowell's birthday. Boo!!",
  "10-08": "it's World Octopus Day!",
  "10-09": "it's World Post Day!",
  "10-10": "it's World Porridge Day!",
  "10-11": "it's National Coming Out Day!",
  "10-12": "it's International Day Against DRM!",
  "10-13": "it's International Day for Natural Disaster Reduction!",
  "10-14": "it's International E-Waste Day!",
  "10-15": "it's World Students' Day!",
  "10-16": "it's World Food Day!",
  "10-17": "it's International Sawfish Day!",
  "10-18": "it's World Okapi Day! They are related to giraffes!",
  "10-19": "it's Oxfordshire Day in England!",
  "10-20": "it's International Sloth Day, so don't move too quickly!",
  "10-21": "it's World Earthworm Day!",
  "10-22": "it's International Wombat Day!",
  "10-23": "it's Mole Day. Yay science!",
  "10-24": "it's International Day of Climate Action! Get involved!",
  "10-25": "it's National Greasy Food Day in the US! Wait... isn't that every day?",
  "10-26": "it's Intersex Awareness Day!",
  "10-27": "it's National Black Cat Day in the UK!",
  "10-28": "it's International Animation Day!",
  "10-29": "it's National Oatmeal Day in the US!",
  "10-30": "it's Mischief Night. Please don't T.P. my site!",
  "10-31": "it's Halloween. Stay Spooky!",
  "11-01": "it's World Vegan Day! Eat some plants today!!",
  "11-02": "it's Dziady, a Slavic pagan festival!",
  "11-03": "it's World Basking Shark Day!",
  "11-04": "it's National Candy Day in the US!",
  "11-05": "so remember remember the fifth of November!",
  "11-06": "International Day for Preventing the Exploitation of the Environment in War and Armed Conflict!",
  "11-07": "National Bittersweet Chocolate with Almonds Day in the US! Very specific!",
  "11-08": "it's Cook Something Bold and Pungent Day! What are you going to make?",
  "11-09": "it's Day of the Skulls in Bolivia!",
  "11-10": "it's National Vanilla Cupcake Day in the US!",
  "11-11": "it's Pepero Day in South Korea! It's similar to Valentine's Day, and chocolate covered cookie sticks are exchanged!",
  "11-12": "it's Father's Day in Indonesia!",
  "11-13": "it's World Kindness Day! Do something nice for someone today!",
  "11-14": "it's National Pickle Day in the US!",
  "11-15": "it's America Recycles Day! Do you?",
  "11-16": "it's Icelandic Language Day!",
  "11-17": "it's Homemade Bread Day! Bake something!!",
  "11-18": "it's National Apple Cider Day in the US!",
  "11-19": "it's National Soup Day in Germany!",
  "11-20": "it's Transgender Day of Remembrance!",
  "11-21": "it's World Television Day!",
  "11-22": "it's Good Spouses Day in Japan!",
  "11-23": "it's National Eat A Cranberry Day in the US!",
  "11-24": "it's Evolution Day!",
  "11-25": "Joe DiMaggio's birthday!",
  "11-26": "it's National Cake Day in the US!",
  "11-27": "Jimi Hendrix's birthday!",
  "11-28": "it's National French Toast Day!",
  "11-29": "it's International Jaguar Day!",
  "11-30": "it's National Mousse Day in the US!",
  "12-01": "it's Eat a Red Apple Day! Preferably not Red Delicious, those taste like sand.",
  "12-02": "Britney Spears' birthday!",
  "12-03": "it's International Day of Persons with Disabilities!",
  "12-04": "it's Wildlife Conservation Day!",
  "12-05": "it's Krampusnacht! Hide yo kids if they've been bad!",
  "12-06": "Ira Gershwin's birthday! I got rhythm!",
  "12-07": "Noam Chomsky's birthday!",
  "12-08": "it's Bodhi Day, the day the Buddha became enlightened!",
  "12-09": "it's National Pastry Day in the US!",
  "12-10": "it's Alfred Nobel Day! He invented dynamite!",
  "12-11": "it's International Mountain Day!",
  "12-12": "on this day in 1787 Pennsylvania ratified the Constitution!",
  "12-13": "on this day in 1577 Francis Drake sets sail from England and begins circumnavigating!",
  "12-14": "it's Monkey Day! Ooo-ooo aaa-aaa!",
  "12-15": "it's National Cupcake Day in the US!",
  "12-16": "it's National Sports Day in Thailand!",
  "12-17": "it's Pan American Aviation Day in the US!",
  "12-18": "it's UN Arabic Language Day!",
  "12-19": "Criss Angel's birthday. MIND FREAK!!",
  "12-20": "it's National Cortado Day in the US! ",
  "12-21": "the Winter Solstice!",
  "12-22": "the Dongzhi Winter Solstice Festival in China!",
  "12-23": "a Festivus for the rest of us!",
  "12-24": "Christmas Eve!",
  "12-25": "Christmas! Ho ho ho!!",
  "12-26": "it's Boxing Day!",
  "12-27": "it's National Fruitcake Day in the US!",
  "12-28": "on this day in 1308, Emperor Hanazono begins his reign over Japan.",
  "12-29": "the fourth day of Kwanzaa and the fifth day of Christmas!",
  "12-30": "it's National Bicarbonate of Soda Day in the US!",
  "12-31": "é vespera de ano novo!"
};
    const today = new Date();
    const key = String(today.getMonth() + 1).padStart(2, '0') + "-" + String(today.getDate()).padStart(2, '0');
    const msg = `Hoje é ${today.toLocaleDateString('pt-BR', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })}, e ${days[key] || " nada de especial esta acontecendo, aparentemente."}`;
  {
  return (
    <div className='natday'>{msg}</div>
  );
};
}


export default FactOfTheDay;
