import './FactOfTheDay.css';

/*
National Day widget made by caminus.neocities.org! Feel free to copy this, modify it, or do whatever you'd like with it.
Add your birthday or your pet's adoption date. This is all for fun.
It will create a <div id="natday"></div> wherever the script is inserted. #natday can be styled however you like.
Linking back to me is appreciated but not necessary. Keep this message intact, or not. The code is yours!
*/



function FactOfTheDay () 
{
  const days = {
  "01-01": "é ano novo!!!",
  "01-02": "é dia mundial dos introvertidos, vamos ficar em casa hoje!!",
  "01-03": "é Dia Internacional do Bem-Estar da Mente e do Corpo, vamos meditar juntos :D",
  "01-04": "é o dia mundial do Braile",
  "01-05": "é o aniversario da criação da primeira tipografia do Brasil, a Impressão Régia",
  "01-06": "é dia da gratidão, OBRIGADO!",
  "01-07": "é o dia do leitor, quantos livros você prometeu de ler esse ano?",
  "01-08": "é o dia do fotografo, click click!",
  "01-09": "nesse dia em 1431 o julgamento da Joana d'Arc começou, e em 1822 foi o dia do Fico",
  "01-10": "foi o dia da primeira assembléia geral das nações unidas",
  "01-11": "é o dia do controle da poluição por agrotóxicos, apoie o seu pequeno produtor local!",
  "01-12": "é o dia em que o Exército Vermelho inicia a grande Ofensiva no Vístula-Oder contra as forças nazistas",
  "01-13": "é o dia da Assinatura do Tratado de Madrid, que substituiu o Tratado de Tordesilhas",
  "01-14": "é o dia internacional da pipa",
  "01-15": "é o dia mundial do compositor, dia de criar uma música em?",
  "01-16": "é o dia dos Cortadores de Cana de Açúcar, agradeça pelo seu melado e por suas pingas!",
  "01-17": "é o dia em que as forças soviéticas e polonesas realizaram a libertação de Varsóvia",
  "01-18": "é o dia internacional do riso :))))",
  "01-19": "é o dia da inauguração da Dutra, rodovia que liga as capitais do Rio e de São Paulo",
  "01-20": "é o dia mundial do queijo, uma das 9 maravilhas do mundo <3",
  "01-21": "é o dia em que Vladimir Lênin, líder da Revolução Russa e principal nome por trás da criação da União Soviética, faleceu aos 53 anos :(",
  "01-22": "é o dia do trabalhador doméstico",
  "01-23": "é o Dia Internacional da Medicina Integrativa",
  "01-24": "é o Dia Internacional da Educação, abrace seu professor hoje",
  "01-25": "é o dia da criação dos Correios e Telégrafos no Brasil além de ser o dia do carteiro",
  "01-26": "é o dia da insurreição pernambucana, vaze holandeses",
  "01-27": "é o Dia Internacional em Memória às Vítimas do Holocausto",
  "01-28": "é o Dia Internacional da Privacidade de Dados",
  "01-29": "é o dia nacional da visibilidade Trans",
  "01-30": "é um dia com tempeiro de vó, dia da Saudade",
  "01-31": "é o Dia Nacional das Reservas Particulares do Patrimônio Natural, Focado em conscientizar a população sobre a conservação da biodiversidade local",
  "02-01": "Dia do tomate :)",
  "02-02": "é Dia de Iemanjá, Axé",
  "02-03": "é o dia nacional do bolo de cenoura, e eu aprendi isso com um gringo",
  "02-04": "é o Dia Mundial contra o Câncer, va fazer seu toque",
  "02-05": "é o dia em que a Apollo 14 pousou na lua",
  "02-06": "é o Dia Internacional da Internet Segura, mate uma big tech hoje",
  "02-07": "é deflagrada a grande greve operária em São Paulo liderada por João da Costa Pimenta, marco que instituiu a comemoração do Dia do Gráfico",
  "02-08": "uma iniciativa global para promover a conscientização sobre a doença e combater o estigma associado a ela deu origem ao Dia da Epilepsia",
  "02-09": "a missão Apollo 14 voltou para a terra e o volêi foi criado",
  "02-10": "é o Dia Mundial das Leguminosas, compre com seu pequeno produtor local!",
  "02-11": "é Dia Internacional das Mulheres e Meninas na Ciência, girl power!",
  "02-12": "nasce o naturalista inglês Charles Darwin, data hoje celebrada internacionalmente como o Dia de Darwin para homenagear suas contribuições à ciência e à teoria da evolução.",
  "02-13": "o astrônomo italiano Galileu Galilei chega a Roma para ser julgado pela Santa Inquisição",
  "02-14": "é o Dia Internacional da Doação de Livros",
  "02-15": "é Lupercália!!!  Um festival histórico, considerado por muitos historiadores como uma das origens das tradições de afeto e amor que hoje culminam no Dia dos Namorados.",
  "02-16": "Após a Revolução Cubana, Fidel Castro assumiu o cargo de primeiro-ministro do país.",
  "02-17": "o supercomputador Deep Blue, da IBM, derrota pela primeira vez o então campeão mundial Garry Kasparov em uma partida(1996)",
  "02-18": "surge a primeira faculdade de medicina do Brasil, a Escola de Cirurgia da Bahia (atual Faculdade de Medicina da Universidade Federal da Bahia)",
  "02-19": "foi instituído o Parque Nacional da Amazônia, o maior parque nacional do país",
  "02-20": "é o Dia Mundial da Justiça Social",
  "02-21": "é o aniversário do meu irmão :D, parabéns mano",
  "02-22": "petróleo jorra pela primeira vez em território brasileiro, no poço de Lobato, localizado em Salvador, Bahia",
  "02-23": "it's National Banana Bread day in the US!",
  "02-24": "it's Twin Peaks Day! Eat some cherry pie!",
  "02-25": "on this day in 138, Emperor Hadrian adopted a son! ...making him the heir.",
  "02-26": "on this day in 364, Valentinian I is proclaimed Roman emperor!",
  "02-27": "it's Doctors' Day in Vietnam!",
  "02-28": "it's National Science Day in India!",
  "02-29": "a Leap Day! Enjoy the extra day!!",
  "03-01": "it's National Peanut Butter Lover's Day in the US!",
  "03-02": "it's National Banana Cream Pie Day in the US!",
  "03-03": "it's World Wildlife Day!",
  "03-04": "it's Marching Band Day. March Forth!",
  "03-05": "on this day in 1616, Copernicus's book On the Revolutions of the Heavenly Spheres was banned by the church!",
  "03-06": "on this day in 12 BC Augustus was named Pontifex Maximus!",
  "03-07": "it's Maritime Day in Slovenia!",
  "03-08": "it's International Women's Day!",
  "03-09": "it's Teachers' Day in Lebanon!",
  "03-10": "it's Mario Day! MAR10, get it? Wahoo!!",
  "03-11": "Leroy Jenkins' birthday! The jazz violinist, not the WoW character.",
  "03-12": "it's World Day Against Cyber Censorship!",
  "03-13": "it's National Elephant Day in Thailand!",
  "03-14": "it's Pi day! 3.14159265358979323846264338327950288419716939937510 and beyond!",
  "03-15": "the Ides of March! Beware!!",
  "03-16": "it's National Panda Day!",
  "03-17": "it's Saint Patty's Day!",
  "03-18": "it's Global Recycling Day! Reduce, reuse recycle!",
  "03-19": "it's Taxonomist Appreciation Day. Go thank your local taxonomist!",
  "03-20": "it's World Sparrow Day! Also, World Frog Day!",
  "03-21": "it's International Day of Forests!",
  "03-22": "it's World Water Day!",
  "03-23": "it's World Meteorological Day!",
  "03-24": "it's National Tree Planting Day in Uganda!",
  "03-25": "it's National Waffle Day in Sweden!",
  "03-26": "it's Science Appreciation Day!",
  "03-27": "it's World Theater Day!",
  "03-28": "on this day in 1978 Three Mile Island's nuclear reactor had a partial meltdown!",
  "03-29": "it's Youth Day in Taiwan!",
  "03-30": "it's International Day of Zero Waste! How little waste can you generate today?",
  "03-31": "it's Trans Day of Visibility!",
  "04-01": "it's April Fools day. Be careful out there!",
  "04-02": "it's National Peanut Butter and Jelly Day in the US!",
  "04-03": "it's World Aquatic Animal Day",
  "04-04": "it's World Rat Day!",
  "04-05": "it's First Contact Day! Vulcans will be here before we know it!",
  "04-06": "it's International Asexuality Day!",
  "04-07": "it's International Beaver Day!",
  "04-08": "the Buddha's Birthday, as celebrated in Japan!",
  "04-09": "on this day in 1860 Edouard-Leon Scott de Martinville made the first known recording of the human voice!",
  "04-10": "it's Sibling Day!",
  "04-11": "it's International Louie Louie Day, give it a listen!",
  "04-12": "on this day in 1961 Yuri Gagarin became the first human to travel into space!",
  "04-13": "on this day in 1204 Constantinople fell to Crusaders in the Fourth Crusade!",
  "04-14": "it's World Quantum Day!",
  "04-15": "it's Tax Day in the US!! Hopefully you'll get some money back this year!",
  "04-16": "it's World Voice Day!",
  "04-17": "it's Bat Appreciation Day! Go thank a bat!",
  "04-18": "it's World Amateur Radio Day!",
  "04-19": "it's Bicycle Day, commemorating the first LSD trip! Stay safe and have fun!",
  "04-20": "you know what that means... blaze it!!!",
  "04-21": "Rome's birthday! Rome eternal!!",
  "04-22": "it's Earth Day!",
  "04-23": "it's International Pallas's Cat day! That's a type of small wild cat, check em out!",
  "04-24": "it's World Day for Laboratory Animals!",
  "04-25": "it's World Malaria Day!",
  "04-26": "it's Arbor Day! Also, National Pretzel Day in the US!",
  "04-27": "it's World Tapir Day and International Hyena Day!",
  "04-28": "it's Sardinian People's Day!",
  "04-29": "it's International Dance Day!",
  "04-30": "it's Hexennacht! A Satanist holiday honoring those who fell victim to superstition and pseudoscience.",
  "05-01": "it's May Day. In addition to an ancient pagan festival, it's the original Labor Day!",
  "05-02": "it's Harry Potter Day! Thanks, Miku Hatsune, for writing such a beloved fantasy series!",
  "05-03": "it's International Sun Day!",
  "05-04": "it's Star Wars Day! May the force be with you!",
  "05-05": "it's Cinco de Mayo!",
  "05-06": "it's International No Diet Day! Eat what makes you feel good!",
  "05-07": "it's Communications Workers' Day in Russia!",
  "05-08": "it's World Donkey Day! Hee-haw!",
  "05-09": "it's Goku Day in Japan! Like, Goku from Dragon Ball!",
  "05-10": "on this day in 1774 Louis XVI and Marie Antoinette became King and Queen of France. Hope it worked out for them.",
  "05-11": "Bobi the dog's birthday! He was reportedly the oldest dog ever, living to be 31!",
  "05-12": "it's International Nurses Day!",
  "05-13": "Hummus Day! Make some hummus! Yum!!",
  "05-14": "David Byrne's birthday! Listen to some Talking Heads!",
  "05-15": "it's International Conscientious Objectors Day!",
  "05-16": "on this day in 1770 a 14-year-old Marie Antoinette marries 15-year-old Louis!",
  "05-17": "it's Galician Literature Day!",
  "05-18": "it's International Museum Day!",
  "05-19": "it's Malcolm X Day!",
  "05-20": "it's World Bee Day! Thank a bee!",
  "05-21": "it's International Tea Day! Cheers!",
  "05-22": "it's International Day for Biological Diversity!",
  "05-23": "it's World Turtle Day!",
  "05-24": "it's European Day of Parks! Enjoy the day!",
  "05-25": "it's Towel Day. Don't Panic!!",
  "05-26": "it's National Paper Airplane Day in the US!",
  "05-27": "Siouxsie Sioux's birthday!",
  "05-28": "it's World Dugong Day, it's not just a Pokemon!",
  "05-29": "it's Castleton Garland Day in Castleton, England! An interesting Celtic folk festival, look it up!",
  "05-30": "it's Kaamatan, a harvest festival in Malaysia!",
  "05-31": "it's World No Tobacco Day!",
  "06-01": "it's World Reef Day!",
  "06-02": "it's National Rocky Road Day!",
  "06-03": "it's World Bicycle Day, go ride a bike if you can!",
  "06-04": "on this day in 1912 Massachusetts became the first state to set a minimum wage!",
  "06-05": "it's World Environment Day!",
  "06-06": "it's National Applesauce Cake Day in the US!",
  "06-07": "it's Journalist Day in Argentina!",
  "06-08": "it's World Oceans Day!",
  "06-09": "it's Coral Triangle Day! Look up some Coral Triangle facts, it's amazing!",
  "06-10": "it's National Iced Tea Day in the US!",
  "06-11": "it's National Corn on the Cob Day in the US!",
  "06-12": "it's National Peanut Butter Cookie Day in the US!",
  "06-13": "it's Inventors' Day in Hungary!",
  "06-14": "it's World Blood Donor Day!",
  "06-15": "it's Global Wind Day!",
  "06-16": "it's Bloomsday. Eat some Irish food and read some Joyce!",
  "06-17": "it's World Croc Day! The animal, not the shoe.",
  "06-18": "a imigração japonesa no Brasil começa quando 781 pessoas chegam ao Porto de Santos a bordo do navio Kasato Maru",
  "06-19": "it's Juneteenth!",
  "06-20": "it's National Vanilla Milkshake Day in the US!",
  "06-21": "it's World Giraffe Day! Also, the solstice!",
  "06-22": "it's World Rainforest Day!",
  "06-23": "it's Autistic Pride Day in Luxembourg!",
  "06-24": "it's Fors Fortuna, an ancient Roman festival to Fortuna!",
  "06-25": "it's World Vitiligo Day!",
  "06-26": "it's National Chocolate Pudding Day in the US!",
  "06-27": "it's Helen Keller Day!",
  "06-28": "it's Tau Day! That's 2pi, the superior constant! Also, twice the pie!",
  "06-29": "it's Engineer's Day in Ecuador!",
  "06-30": "it's Asteroid Day.",
  "07-01": "the start of Pride Month!!",
  "07-02": "on this day in 1494 the Treaty of Tordesillas was ratified by Spain!",
  "07-03": "it's Eat Beans Day! The more you eat the more you... you know...",
  "07-04": "it's US Independence Day. Go read some Frederick Douglass.",
  "07-05": "it's National Apple Turnover Day in the US!",
  "07-06": "it's Kupala Night, a Slavic solstice festival!",
  "07-07": "it's World Chocolate Day!",
  "07-08": "it's National Chocolate with Almonds Day in the US!",
  "07-09": "it's National Sugar Cookie Day in the US! They are easy to bake!",
  "07-10": "it's  Pizza Day in Brazil!",
  "07-11": "it's National Blueberry Muffin Day in the US!",
  "07-12": "it's National Pecan Pie Day in the US!",
  "07-13": "on this day in 1930 the first World Cup happens in Uruguay!",
  "07-14": "it's Shark Awareness Day! Be aware, sharks need our help!",
  "07-15": "it's Gummi Worm Day!",
  "07-16": "it's Fresh Spinach Day!",
  "07-17": "it's National Peach Ice Cream Day in the US!",
  "07-18": "it's Nelson Mandela International Day!",
  "07-19": "on this day in 64, the Great Fire of Rome starts, rages for six days, and destroys half the city.",
  "07-20": "it's National Fortune Cookie Day in the US! What's your fortune?",
  "07-21": "it's Junk Food Day, mmmmm...",
  "07-22": "it's Pi Approximation Day! 22 over 7 is a good enough reason to eat some pie!",
  "07-23": "it's National Vanilla Ice Cream Day in the US!",
  "07-24": "it's Children's Day in Vanuatu!",
  "07-25": "it's National Hot Fudge Sundae Day in the US!",
  "07-26": "it's International Day for the Conservation of the Mangrove Ecosystems!",
  "07-27": "it's National Sleepy Head Day in Finland!",
  "07-28": "it's World Nature Conservation Day!",
  "07-29": "Garfield's favorite day, National Lasagna Day!!",
  "07-30": "it's International Day of Friendship!",
  "07-31": "it's National Raspberry Cake Day in the US!",
  "08-01": "the start of South Asian Heritage Month in the UK!",
  "08-02": "it's International Friendship Day!",
  "08-03": "on this day in 1527 John Rut sends the first letter from North America to Europe!",
  "08-04": "it's International Clouded Leopard Day!",
  "08-05": "it's World Tomistoma Day! That's a genus of crocodilian!",
  "08-06": "it's National Root Beer Float Day in the US!",
  "08-07": "it's Youth Day in Kiribati!",
  "08-08": "it's International Moon Bear Day!",
  "08-09": "artist Tove Jansson's birthday! She made Moomins!",
  "08-10": "it's World Lion Day! Rawr!!!",
  "08-11": "it's Mountain Day in Japan!",
  "08-12": "World Elephant Day! Also, World Hirola Day, a critically endangered antelope!",
  "08-13": "it's International Lefthanders Day!",
  "08-14": "it's National Navajo Code Talkers Day!",
  "08-15": "it's National Lemon Meringue Pie Day in the US!",
  "08-16": "it's Daimonji in Japan! Big bonfires are lit!",
  "08-17": "Mae West's birthday!",
  "08-18": "it's National Science Day in Thailand!",
  "08-19": "it's World Orangutan Day!",
  "08-20": "it's World Mosquito Day! Commemorating the discovery that they carry... malaria...",
  "08-21": "it's World Senior Citizen's Day! Do something nice for an older person!",
  "08-22": "it's National Eat A Peach Day in the US!",
  "08-23": "on this day in 79, Mount Vesuvius begins stirring... and it's the feast of Vulcan, god of fire!",
  "08-24": "it's National Waffle Day in the US!",
  "08-25": "it's National Banana Split Day in the US!",
  "08-26": "it's World African Wild Dog Day!",
  "08-27": "it's National Banana Lovers Day in the US!",
  "08-28": "it's National Cherry Turnover Day in the US!",
  "08-29": "it's International Day against Nuclear Tests!",
  "08-30": "it's International Whale Shark Day!",
  "08-31": "it's Trail Mix Day!",
  "09-01": "it's World Beach Day!",
  "09-02": "it's National Blueberry Popsicle Day in the US!",
  "09-03": "on this day in 1189 Richard the Lionheart is crowned king!",
  "09-04": "it's National Macadamia Nut Day in the US!",
  "09-05": "it's Amazon Rainforest Day!",
  "09-06": "on this day in 1628 the Puritans settled in Salem.",
  "09-07": "it's International Day of Clean Air for blue skies!",
  "09-08": "it's World Physical Therapy Day!",
  "09-09": "it's Chrysanthemum Day in Japan!",
  "09-10": "it's World Suicide Prevention Day!",
  "09-11": "it's National Hot Cross Bun Day, not just a song!",
  "09-12": "it's World Dolphin Day!",
  "09-13": "it's National Peanut Day in the US!",
  "09-14": "it's Hoagie Day!",
  "09-15": "it's International Colugo Day! That's a flying lemur!!",
  "09-16": "it's International Day for the Preservation of the Ozone Layer!",
  "09-17": "it's World Manta Day!",
  "09-18": "it's World Water Monitoring Day, so test your water!",
  "09-19": "it's Talk like a Pirate Day, yarr!!",
  "09-20": "it's National Punch Day in the US! The drink, not the verb.",
  "09-21": "that means you better remember tonight!",
  "09-22": "it's Car Free Day! Try a bus, train, or something else if you can!",
  "09-23": "it's Celebrate Bisexuality Day!",
  "09-24": "it's World Gorilla Day!",
  "09-25": "bell hooks' birthday!",
  "09-26": "it's World Cassowary Day! It's a freaky looking bird!",
  "09-27": "it's World Tourism Day!",
  "09-28": "it's World Rabies Day!",
  "09-29": "it's International Day of Awareness of Food Loss and Waste! Around 17% of food is wasted worldwide!",
  "09-30": "it's National Hot Mulled Cider Day in the US!",
  "10-01": "it's World Vegetarian Day! Go eat a plant!",
  "10-02": "Mahatma Gandhi's birthday!",
  "10-03": "it's Mean Girls Day! Wear something pink!",
  "10-04": "it's World Animal Day!",
  "10-05": "it's World Teachers' Day!",
  "10-06": "it's National Badger Day!",
  "10-07": "Simon Cowell's birthday. Boo!!",
  "10-08": "it's World Octopus Day!",
  "10-09": "it's World Post Day!",
  "10-10": "it's World Porridge Day!",
  "10-11": "it's National Coming Out Day!",
  "10-12": "it's International Day Against DRM!",
  "10-13": "it's International Day for Natural Disaster Reduction!",
  "10-14": "it's International E-Waste Day!",
  "10-15": "it's World Students' Day!",
  "10-16": "it's World Food Day!",
  "10-17": "it's International Sawfish Day!",
  "10-18": "it's World Okapi Day! They are related to giraffes!",
  "10-19": "it's Oxfordshire Day in England!",
  "10-20": "it's International Sloth Day, so don't move too quickly!",
  "10-21": "it's World Earthworm Day!",
  "10-22": "it's International Wombat Day!",
  "10-23": "it's Mole Day. Yay science!",
  "10-24": "it's International Day of Climate Action! Get involved!",
  "10-25": "it's National Greasy Food Day in the US! Wait... isn't that every day?",
  "10-26": "it's Intersex Awareness Day!",
  "10-27": "it's National Black Cat Day in the UK!",
  "10-28": "it's International Animation Day!",
  "10-29": "it's National Oatmeal Day in the US!",
  "10-30": "it's Mischief Night. Please don't T.P. my site!",
  "10-31": "it's Halloween. Stay Spooky!",
  "11-01": "it's World Vegan Day! Eat some plants today!!",
  "11-02": "it's Dziady, a Slavic pagan festival!",
  "11-03": "it's World Basking Shark Day!",
  "11-04": "it's National Candy Day in the US!",
  "11-05": "so remember remember the fifth of November!",
  "11-06": "International Day for Preventing the Exploitation of the Environment in War and Armed Conflict!",
  "11-07": "National Bittersweet Chocolate with Almonds Day in the US! Very specific!",
  "11-08": "it's Cook Something Bold and Pungent Day! What are you going to make?",
  "11-09": "it's Day of the Skulls in Bolivia!",
  "11-10": "it's National Vanilla Cupcake Day in the US!",
  "11-11": "it's Pepero Day in South Korea! It's similar to Valentine's Day, and chocolate covered cookie sticks are exchanged!",
  "11-12": "it's Father's Day in Indonesia!",
  "11-13": "it's World Kindness Day! Do something nice for someone today!",
  "11-14": "it's National Pickle Day in the US!",
  "11-15": "it's America Recycles Day! Do you?",
  "11-16": "it's Icelandic Language Day!",
  "11-17": "it's Homemade Bread Day! Bake something!!",
  "11-18": "it's National Apple Cider Day in the US!",
  "11-19": "it's National Soup Day in Germany!",
  "11-20": "it's Transgender Day of Remembrance!",
  "11-21": "it's World Television Day!",
  "11-22": "it's Good Spouses Day in Japan!",
  "11-23": "it's National Eat A Cranberry Day in the US!",
  "11-24": "it's Evolution Day!",
  "11-25": "Joe DiMaggio's birthday!",
  "11-26": "it's National Cake Day in the US!",
  "11-27": "Jimi Hendrix's birthday!",
  "11-28": "it's National French Toast Day!",
  "11-29": "it's International Jaguar Day!",
  "11-30": "it's National Mousse Day in the US!",
  "12-01": "it's Eat a Red Apple Day! Preferably not Red Delicious, those taste like sand.",
  "12-02": "Britney Spears' birthday!",
  "12-03": "it's International Day of Persons with Disabilities!",
  "12-04": "it's Wildlife Conservation Day!",
  "12-05": "it's Krampusnacht! Hide yo kids if they've been bad!",
  "12-06": "Ira Gershwin's birthday! I got rhythm!",
  "12-07": "Noam Chomsky's birthday!",
  "12-08": "it's Bodhi Day, the day the Buddha became enlightened!",
  "12-09": "it's National Pastry Day in the US!",
  "12-10": "it's Alfred Nobel Day! He invented dynamite!",
  "12-11": "it's International Mountain Day!",
  "12-12": "on this day in 1787 Pennsylvania ratified the Constitution!",
  "12-13": "on this day in 1577 Francis Drake sets sail from England and begins circumnavigating!",
  "12-14": "it's Monkey Day! Ooo-ooo aaa-aaa!",
  "12-15": "it's National Cupcake Day in the US!",
  "12-16": "it's National Sports Day in Thailand!",
  "12-17": "it's Pan American Aviation Day in the US!",
  "12-18": "it's UN Arabic Language Day!",
  "12-19": "Criss Angel's birthday. MIND FREAK!!",
  "12-20": "it's National Cortado Day in the US! ",
  "12-21": "the Winter Solstice!",
  "12-22": "the Dongzhi Winter Solstice Festival in China!",
  "12-23": "a Festivus for the rest of us!",
  "12-24": "Christmas Eve!",
  "12-25": "Christmas! Ho ho ho!!",
  "12-26": "it's Boxing Day!",
  "12-27": "it's National Fruitcake Day in the US!",
  "12-28": "on this day in 1308, Emperor Hanazono begins his reign over Japan.",
  "12-29": "the fourth day of Kwanzaa and the fifth day of Christmas!",
  "12-30": "it's National Bicarbonate of Soda Day in the US!",
  "12-31": "é vespera de ano novo!"
};
    const today = new Date();
    const key = String(today.getMonth() + 1).padStart(2, '0') + "-" + String(today.getDate()).padStart(2, '0');
    const msg = `Hoje é ${today.toLocaleDateString('pt-BR', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })}, e ${days[key] || " nada de especial esta acontecendo, aparentemente."}`;
  {
  return (
    <div className='natday'>{msg}</div>
  );
};
}


export default FactOfTheDay;
